---
# ------------------------------------------------------------------
#        configure user equivalence for OS oracle user 
# (1) Generate SSH keys 
# (2) Fetch the keyfile from one server to another
# (3) Copy the key add to authorized_keys
# ------------------------------------------------------------------
- block:
  - name: SSH KeyGen command for grid
    become_user: grid
    tags: run
    shell: >
      ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
      creates="~/.ssh/id_rsa"

  - name: Fetch the keyfile from one server to another for grid
    tags: run
    become_user: grid
    fetch:
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/{{inventory_hostname}}-id_rsa.pub"
      flat: yes

  - name: Copy the key add to authorized_keys using Ansible module
    tags: run
    authorized_key:
      user: grid
      state: present
      key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
    when: "item != inventory_hostname"
    with_items:
      - "{{ groups['opsdevt'] }}"
