---
# ------------------------------------------------------------------
#         Create OS users for Oracle Software Installation
# ------------------------------------------------------------------
# - name: Create user
#   user: name={{ oracle_user }} groups={{ item }} password="{{ oraclepasswd | password_hash('sha512') }}"
#   with_items: "{{ oracle_groups }}"
- name: User | Add Oracle user
  user: name={{ item.username }}  group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }} generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
  with_items: "{{oracle_users}}"
  tags:
    - user

# - name: User | Add Grid user
#   user: name={{ item.username }}  group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }} generate_ssh_key=yes append=yes state=present password={{ item.passwd }}
#   when: role_separation
#   with_items: "{{grid_users}}"
#   tags:
#     - user