

# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

# You might need this in the session.
# export SSH_AUTH_SOCK=""

# Variables
params = YAML.load_file 'config/vagrant.yml'
var_box                     = params['shared']['box']
var_non_rotational          = params['shared']['non_rotational']

var_asm_crs_disk_1          = params['shared']['asm_crs_disk_1']
var_asm_crs_disk_2          = params['shared']['asm_crs_disk_2']
var_asm_crs_disk_3          = params['shared']['asm_crs_disk_3']
var_asm_crs_disk_size       = params['shared']['asm_crs_disk_size']
var_asm_data_disk_1         = params['shared']['asm_data_disk_1']
var_asm_data_disk_size      = params['shared']['asm_data_disk_size']
var_asm_reco_disk_1         = params['shared']['asm_reco_disk_1']
var_asm_reco_disk_size      = params['shared']['asm_reco_disk_size']

var_vm_name                 = params['node1']['vm_name']
var_mem_size                = params['node1']['mem_size']
var_cpus                    = params['node1']['cpus']
var_public_ip               = params['node1']['public_ip']
var_private_ip              = params['node1']['private_ip']
var_u01_disk                = params['node1']['u01_disk']


Vagrant.configure("2") do |config|
 
  config.vm.box = var_box

  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 5500, host: 5500

  config.vm.network "private_network", ip: var_public_ip
  config.vm.network "private_network", ip: var_private_ip, virtualbox__intnet: "private"

  config.vm.synced_folder "config", "/vagrant_config"
  config.vm.synced_folder "shared_scripts", "/vagrant_scripts"
  #config.vm.synced_folder "../software", "/vagrant_software"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = var_mem_size
    vb.cpus   = var_cpus
    vb.name   = var_vm_name

    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', '0', '--nonrotational', var_non_rotational]
    unless File.exist?(var_u01_disk)
      vb.customize ['createhd', '--filename', var_u01_disk, '--size', 100 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', var_u01_disk, '--nonrotational', var_non_rotational]
  end
  config.vm.provision "shell", inline: <<-SHELL
    sh /vagrant_scripts/run.sh
  SHELL
end
