---
 
- name: copy response file to the target database server
  become_user: oracle
  when: inventory_hostname in groups['opsdevt']
  #remote_user: "{{ root_user }}"
  copy: src=templates/{{ item }} dest={{ oracle_tmp }} mode=0775
  with_items:
    - db_install.rsp
  

- name: set inline changes (common)
  lineinfile: 
    path: /tmp/db_install.rsp
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }}={{ item.value }}"
  with_items:
    - { regex: oracle.install.responseFileVersion, value: "/oracle/install/rspfmt_dbinstall_response_schema_v11_2_0" }
    - { regex: oracle.install.option, value: "{{ install_mode }}" }
    - { regex: ORACLE_HOSTNAME, value: "{{ ansible_hostname }}" }
    - { regex: UNIX_GROUP_NAME, value: "{{ oracle_group[0].name }}" }
    - { regex: INVENTORY_LOCATION, value: "{{ ORA_INVENTORY}}" }
    - { regex: SELECTED_LANGUAGES, value: "en" }
    - { regex: ORACLE_HOME, value: "{{ ORACLE_HOME }}" }
    - { regex: ORACLE_BASE, value: "{{ oracle_base }}" }
    - { regex: oracle.install.db.InstallEdition, value: "{{ oracle_edition }}" }
  #  - { regex: oracle.install.db.isCustomInstall, value: "false" }
    - { regex: oracle.install.db.DBA_GROUP, value: "{{ oracle_dba_group[0].name }}" }
    - { regex: oracle.install.db.OPER_GROUP, value: "{{ oracle_dba_group[0].name }}" }
    - { regex: oracle.install.db.config.starterdb.type, value: "GENERAL_PURPOSE" }
    - { regex: oracle.install.db.config.starterdb.globalDBName, value: "{{ oracle_db_name }}" }
    - { regex: oracle.install.db.config.starterdb.SID, value: "{{ oracle_db_name }}" }
    - { regex: oracle.install.db.config.starterdb.characterSet, value: "AL32UTF8" }
    - { regex: oracle.install.db.config.starterdb.memoryLimit, value: "{{ oracle_db_mem }}" }
    - { regex: oracle.install.db.config.starterdb.memoryOption, value: "true" }
    - { regex: oracle.install.db.config.starterdb.installExampleSchemas, value: "false" }
    - { regex: oracle.install.db.config.starterdb.password.ALL, value: "{{ oracle_db_syspass }}" }
    - { regex: oracle.install.db.config.starterdb.storageType, value: "{{ oracle_storage_type }}" }
    - { regex: oracle.install.db.config.starterdb.fileSystemStorage.dataLocation, value: "{{ oracle_base }}/data" }
    - { regex: SECURITY_UPDATES_VIA_MYORACLESUPPORT, value: "false" }
    - { regex: DECLINE_SECURITY_UPDATES, value: "true" }

#- name: set inline changes (my oracle support for 11.2.0.4)
#  lineinfile: 
#    path: /tmp/oracle/db_install.rsp
#    regexp: "^{{ item.regex }}"
#    line: "{{ item.regex }}={{ item.value }}"
#  with_items:

- name: set inline changes (12c)
  lineinfile: 
    path: /tmp/db_install.rsp
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }}={{ item.value }}"
  with_items:
    - { regex: oracle.install.db.OSDBA_GROUP, value: "dba" }
    - { regex: oracle.install.db.OSOPER_GROUP, value: "oper" }
    - { regex: oracle.install.db.OSBACKUPDBA_GROUP, value: "backupdba" }
    - { regex: oracle.install.db.OSDGDBA_GROUP, value: "dgdba" }
    - { regex: oracle.install.db.OSKMDBA_GROUP, value: "kmdba" }
    - { regex: oracle.install.db.OSRACDBA_GROUP, value: "racdba" }
  #when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "12.2.0"